### PR TITLE
Renamed binaries from bitcoin to inutoshi.

### PR DESCRIPTION
**Pull request by rnicoll**
This should produce correctly named binaries. Tested under Linux, please verify with Windows & OS X.

### CODE REVIEW

**Comment by leofidus** [comment]
On Windows I get

```
  CXX    inutoshid.o
make[3]: *** No rule to make target `inutoshid-res.o', needed by `inutoshid.exe'
```

**Comment by rnicoll** [comment]
Have tried assembling a Windows build environment, but so far without success, so working a little blind here.

Can you try the further commits, see if they resolve this please?

**Comment by leofidus** [comment]
I f that's you wrestling with the build scripts blindfolded then you are really good at that :D 

It builds correctly on Windows. Only bitcoin-cli.exe still has the old name. I will try with gitian later.

**Comment by leofidus** [comment]
great, works

**Pull request merged**
